version: '3.8'

services:
  mouse-detector:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
      - ./mouse_data:/app/mouse_data
      - ./weights:/app/weights
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0 